language: python
python:
  - "2.7"
# commands to install dependencies
before_install:
  - git clone https://github.com/ewels/MultiQC.git
  - cd MultiQC
  - python setup.py -q install
  - cd ..
install:
  - python setup.py -q install
  - git clone https://github.com/ewels/MultiQC_TestData.git test_data
  - cd test_data
# commands to run tests
script:
  - multiqc data/bcbio/*
  
